### ISSUE TITLE
`download_dataset()` fails

### ISSUE THREAD

**Issue by BjoernHaefner** [za-cheng/WildLight#4]
Thanks for the user friendly setup of cloning, conda env installation and running.
However when first running I got the following error
```
$ python exp_runner.py --case legocar --conf confs/synthetic.conf --mode train --download_dataset
Hello Wooden
[connectionpool.py:1001 -            _new_conn() ] Starting new HTTPS connection (1): drive.google.com:443
[connectionpool.py:456 -        _make_request() ] https://drive.google.com:443 "GET /uc?id=1xJjPWSKT_CfTFVdvrxRXFgHSO_RZV7UN HTTP/1.1" 200 None
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1xJjPWSKT_CfTFVdvrxRXFgHSO_RZV7UN 

Traceback (most recent call last):
  File "exp_runner.py", line 677, in <module>
    runner = Runner(args.conf, args.mode, args.case, args.is_continue, args.download_dataset)
  File "exp_runner.py", line 58, in __init__
    self.download_dataset() # download dataset to default location
  File "exp_runner.py", line 162, in download_dataset
    gdown.extractall("datasets/legocar.zip", "datasets")
  File "/usr/wiss/haefner/miniconda3/envs/wildlight/lib/python3.8/site-packages/gdown/extractall.py", line 46, in extractall
    with opener(path, mode) as f:
  File "/usr/wiss/haefner/miniconda3/envs/wildlight/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/legocar.zip'
```

I had to manually download the data set in the end.

**Comment by BjoernHaefner** [comment]
`pip install --upgrade --no-cache-dir gdown` solved it!
Taken from [here](https://stackoverflow.com/a/71176719)

So it seems I had to update gdown from `4.2.0` to `4.7.1`

I guess if you change the [environ.yaml](https://github.com/za-cheng/WildLight/blob/86bd3600220f54a1f354badc8c979425051b18d7/environ.yaml#L122) file, it should be fine.
